repos:
  - repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.9.0
    hooks:
      - id: pre-commit-update # Autoupdate pre-commit hooks

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks # Check for secrets

  - repo: https://github.com/executablebooks/mdformat
    rev: 1.0.0
    hooks:
      - id: mdformat # Format Markdown files.
        additional_dependencies:
          - mdformat-gfm>=1.0.0 # Support GitHub Flavored Markdown.

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v9.4.0
    hooks:
      - id: cspell # Spell check files.
        args: ["--config", ".cspell.json"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict # Check for files with names that differ only in case.
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer # Ensure files end with a newline.
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext", "md"] # Preserve Markdown hard line breaks.

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.407
    hooks:
      - id: pyright # Type-checking
        # Explicit args are needed to avoid pyright from using the system Python
        args: ["-p", "pyproject.toml", "--pythonpath", ".venv/bin/python"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10
    hooks:
      - id: ruff-check # Lint code
      - id: ruff-format # Format code

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.18
    hooks:
      - id: uv-lock # Update the uv lockfile
